name: Jekyll Demo

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build site
      run: jekyll build
    - name: Test site
      run: bundle exec htmlproofer ./_site --disable-external
